version: "3.9"

services:
  postgres-seguro:
    build: .
    container_name: farmaec_pg_seguro
    environment:
      POSTGRES_DB: farmaec
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ClaveSuperAdmin2026!
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "ssl=on"
      - "-c"
      - "ssl_cert_file=/var/lib/postgresql/server.crt"
      - "-c"
      - "ssl_key_file=/var/lib/postgresql/server.key"
      - "-c"
      - "log_connections=on"
      - "-c"
      - "log_disconnections=on"
      - "-c"
      - "log_statement=mod"

volumes:
  pgdata:
